Moved project files.

diff --git a/bin/generate-evdev b/bin/generate-evdev
--- a/bin/generate-evdev
+++ b/bin/generate-evdev
@@ -9,15 +9,17 @@
 # Maintainer(s):  Alex Portell <github.com/portellam>
 #
 
+# TODO: create cronjob of last input.
+
 # <params>
   declare -gA ALL_INPUT_EVENT_DICTIONARY KEYBOARD_INPUT_INDEX_DICTIONARY MOUSE_INPUT_INDEX_DICTIONARY # OTHER_INPUT_INDEX_DICTIONARY
 
   declare -r SCRIPT_NAME="$( basename ${0} )"
-  declare -r REPO_NAME="generate-evdev"
+  declare -r SOURCE_DIR="/usr/local/etc/${SCRIPT_NAME}.d/"
 
   declare -ar FILE_WATERMARK=(
-    "# Generated by 'portellam/${REPO_NAME}'"
-    "# WARNING: Any modifications to this file will be modified by '${REPO_NAME}'"
+    "# Generated by 'portellam/${SCRIPT_NAME}'"
+    "# WARNING: Any modifications to this file will be modified by '${SCRIPT_NAME}'"
     "#"
   )
 
@@ -41,7 +43,8 @@
     declare -g DUMP_XML=false
     # declare -g EXCLUSIVE_KBM=true
     declare -g INCLUDE_HUGEPAGES=false
-    declare -g OUTPUT_EVENT_PATHS=false
+    declare -g OUTPUT_EVENT_PATHS=true
+    declare -g OUTPUT_INPUT_PATHS=true
     declare -g RESTART_SERVICE=false
     declare -g SET_PERMISSIONS_TO_USER=false
     declare -g UNDO_CHANGES=false
@@ -49,12 +52,32 @@
   # <summary>Filenames</summary>
     declare -gr APPARMOR_QEMU_DEST_PATH="/etc/apparmor.d/local/abstractions/libvirt-qemu"
     declare -gr QEMU_DEST_PATH="/etc/libvirt/qemu.conf"
-    declare -gr QEMU_SRC_PATH=$( dirname "${0}" )"/qemu.conf"
+    declare -gr QEMU_SRC_PATH="${SOURCE_DIR}qemu.conf"
+    declare -gr XML_DEST_PATH="${SOURCE_DIR}evdev.xml"
 
   declare -r LOGIN_USER=$( who am i | awk '{print $1}' )
 # </params>
 
 # <functions>
+  function main
+  {
+    if ! is_sudo_user \
+      || ! get_options "$@" \
+      || ! get_evdev \
+      || ! sort_evdev \
+      || ! print_evdev \
+      || ! prepare_files; then
+      return 1
+    fi
+
+    if ! write_to_files; then
+      print_fail_to_log "Could not generate Evdev setup."
+      return 1
+    fi
+
+    print_pass_to_log "Generated Evdev setup."
+  }
+
   # <summary>Usage</summary>
     function is_option_print_help
     {
@@ -103,9 +126,18 @@
         return 1
       fi
 
-      OUTPUT_EVENT_PATHS=true
+      OUTPUT_INPUT_PATHS=false
       print_output_to_log "Evdev output exclusive to Event paths."
+    }
 
+    function is_option_output_input_paths
+    {
+      if [[ "${1}" != "--output-input-paths" ]]; then
+        return 1
+      fi
+
+      OUTPUT_EVENT_PATHS=false
+      print_output_to_log "Evdev output exclusive to Input paths."
     }
 
     function is_option_restart_service
@@ -158,14 +190,19 @@
 
     function parse_this_option
     {
-      is_option_print_help "$@" && return 0
-      is_option_dump_xml "$@" && return 0
-      is_option_include_hugepages "$@" && return 0
-      # is_option_include_only_keyboard_and_mouse "$@" && return 0
-      is_option_output_event_paths "$@" && return 0
-      is_option_restart_service "$@" && return 0
-      is_option_set_permissions_to_user "$@" && return 0
-      is_option_undo_changes "$@" && return 0
+      # || is_option_include_only_keyboard_and_mouse "$@" \
+
+      if is_option_print_help "$@" \
+        || is_option_dump_xml "$@" \
+        || is_option_include_hugepages "$@" \
+        || is_option_output_event_paths "$@" \
+        || is_option_output_input_paths "$@" \
+        || is_option_restart_service "$@" \
+        || is_option_set_permissions_to_user "$@" \
+        || is_option_undo_changes "$@"; then
+        return 0
+      fi
+
       return 1
     }
 
@@ -210,9 +247,10 @@
         # NOTE: Given Evdev currently likely does not support devices outside of Keyboards and Mice, I will comment this out for now.
         # "  --kbm-only\t\tInclude only Keyboard and/or Mouse related devices in Evdev."
 
-        "  --output-event-paths\tOutput Event device paths, instead of Input device paths."
+        "  --output-event-paths\tOutput Event device paths only."
+        "  --output-input-paths\tOutput Input device paths only."
         "  --restart-service\tRestart Libvirtd system service after setup."
-        "  --set-user\tSets user ownership of Libvirt Input devices to current user. Default is root."
+        "  --set-user\t\tSets user ownership of Libvirt Input devices to current user. Default is root."
         "  --undo-changes\tUndo changes; restore file backups."
       )
 
@@ -223,7 +261,7 @@
   # <summary>Loggers/summary>
     function print_error_to_log
     {
-        echo -e "${PREFIX_ERROR}${1}" >&2
+      echo -e "${PREFIX_ERROR}${1}" >&2
     }
 
     function print_fail_to_log
@@ -234,6 +272,11 @@
     function print_output_to_log
     {
       echo -e "${PREFIX}${1}" >&1
+    }
+
+    function print_pass_to_log
+    {
+      echo -e "${PREFIX_PASS}${1}" >&1
     }
 
   # <summary>Data-type validation</summary>
@@ -311,6 +354,14 @@
       fi
     }
 
+    function is_sudo_user
+    {
+      if [[ $( whoami ) != "root" ]]; then
+        print_error_to_log "User is not sudo or root."
+        return 1
+      fi
+    }
+
     function print_evdev
     {
       echo -e "Below is a list of referenced device IDs, and their actual device IDs (Event and Input devices, respectively)."
@@ -342,48 +393,123 @@
       done
 
       echo -e "\nYou may copy the following XML output, and append to a virtual machine's XML file.\n"
-      echo -e "<qemu:commandline>"
+
+      local -r qemu_begin_tag="<qemu:commandline>"
+      local -r qemu_end_tag="</qemu:commandline>"
+      local -r qemu_object="\t<qemu:arg value="-object"/>"
+
+      echo "${qemu_begin_tag}"
+
+      if "${DUMP_XML}"; then
+        if ! sudo rm --force "${XML_DEST_PATH}" &> /dev/null; then
+          print_error_to_log "Could not delete XML file."
+        fi
+
+        dump_xml_file_contents+=( "${qemu_begin_tag}" )
+      fi
+
+      local -i x=1
+      local -i y=2
 
       for input_device in "${!KEYBOARD_INPUT_INDEX_DICTIONARY[@]}"; do
-        local -i index="${KEYBOARD_INPUT_INDEX_DICTIONARY["${input_device}"]}"
         local event_device="${ALL_INPUT_EVENT_DICTIONARY["${input_device}"]}"
-        echo -e "\t<qemu:arg value="-object"/>"
+        local event_device_output="\t<qemu:arg value="input-linux,id=kbd${x},evdev=/dev/input/${event_device},grab_all=on,repeat=on"/>"
+        local input_device_output="\t<qemu:arg value="input-linux,id=kbd${y},evdev=/dev/input/by-id/${input_device},grab_all=on,repeat=on"/>"
 
         if "${OUTPUT_EVENT_PATHS}"; then
-          echo -e "\t<qemu:arg value="input-linux,id=kbd${index},evdev=/dev/input/${event_device},grab_all=on,repeat=on"/>"
-        else
-          echo -e "\t<qemu:arg value="input-linux,id=kbd${index},evdev=/dev/input/by-id/${input_device},grab_all=on,repeat=on"/>"
+          echo -e "${qemu_object}\n${event_device_output}"
+
+          if "${DUMP_XML}"; then
+          dump_xml_file_contents+=(  )
+            dump_xml_file_contents+=( "${qemu_object}" "${event_device_output}" )
+          fi
         fi
+
+        if "${OUTPUT_INPUT_PATHS}"; then
+          echo -e "${qemu_object}\n${input_device_output}"
+
+          if "${DUMP_XML}"; then
+            dump_xml_file_contents+=( "${qemu_object}" "${input_device_output}" )
+          fi
+        fi
+
+        x=$(( x + 2 ))
+        y=$(( y + 2 ))
       done
+
+      local -i x=1
+      local -i y=2
 
       for input_device in "${!MOUSE_INPUT_INDEX_DICTIONARY[@]}"; do
-        local -i index="${MOUSE_INPUT_INDEX_DICTIONARY["${input_device}"]}"
         local event_device="${ALL_INPUT_EVENT_DICTIONARY["${input_device}"]}"
-        echo -e "\t<qemu:arg value="-object"/>"
+        local event_device_output="\t<qemu:arg value="input-linux,id=mouse${x},evdev=/dev/input/${event_device}"/>"
+        local input_device_output="\t<qemu:arg value="input-linux,id=mouse${y},evdev=/dev/input/by-id/${input_device}"/>"
 
         if "${OUTPUT_EVENT_PATHS}"; then
-          echo -e "\t<qemu:arg value="input-linux,id=mouse${index},evdev=/dev/input/${event_device}"/>"
-        else
-          echo -e "\t<qemu:arg value="input-linux,id=mouse${index},evdev=/dev/input/by-id/${input_device}"/>"
+          echo -e "${qemu_object}\n${event_device_output}"
+
+          if "${DUMP_XML}"; then
+          dump_xml_file_contents+=(  )
+            dump_xml_file_contents+=( "${qemu_object}" "${event_device_output}" )
+          fi
         fi
+
+        if "${OUTPUT_INPUT_PATHS}"; then
+          echo -e "${qemu_object}\n${input_device_output}"
+
+          if "${DUMP_XML}"; then
+            dump_xml_file_contents+=( "${qemu_object}" "${input_device_output}" )
+          fi
+        fi
+
+        x=$(( x + 2 ))
+        y=$(( y + 2 ))
       done
 
-      # # NOTE: Given Evdev currently likely does not support devices outside of Keyboards and Mice, I will comment this out for now.
+      # local -i x=1
+      # local -i y=2
+
+      # NOTE: Given Evdev currently likely does not support devices outside of Keyboards and Mice, I will comment this out for now.
       # if ! "${EXCLUSIVE_KBM}"; then
       #   for input_device in "${!OTHER_INPUT_INDEX_DICTIONARY[@]}"; do
-      #     local -i index="${OTHER_INPUT_INDEX_DICTIONARY["${input_device}"]}"
-      #     # echo -e "\t<qemu:arg value="-object"/>"
+      #     local event_device="${ALL_INPUT_EVENT_DICTIONARY["${input_device}"]}"
+      #     local event_device_output="\t<qemu:arg value="input-linux,id=PLACEHOLDER${x},evdev=/dev/input/${event_device}"/>"
+      #     local input_device_output="\t<qemu:arg value="input-linux,id=PLACEHOLDER${y},evdev=/dev/input/by-id/${input_device}"/>"
 
-      #     # TODO: Replace "PLACEHOLDER" with appropriate device ID.
-      #       if "${OUTPUT_EVENT_PATHS}"; then
-      #         echo -e "\t<qemu:arg value="input-linux,id=PLACEHOLDER${index},evdev=/dev/input/${event_device}"/>"
-      #       else
-      #         echo -e "\t<qemu:arg value="input-linux,id=PLACEHOLDER${index},evdev=/dev/input/by-id/${input_device}"/>"
+      #     if "${OUTPUT_EVENT_PATHS}"; then
+      #       echo -e "${qemu_object}\n${event_device_output}"
+
+      #       if "${DUMP_XML}"; then
+      #       dump_xml_file_contents+=(  )
+      #         dump_xml_file_contents+=( "${qemu_object}" "${event_device_output}" )
       #       fi
+      #     fi
+
+      #     if "${OUTPUT_INPUT_PATHS}"; then
+      #       echo -e "${qemu_object}\n${input_device_output}"
+
+      #       if "${DUMP_XML}"; then
+      #         dump_xml_file_contents+=( "${qemu_object}" "${input_device_output}" )
+      #       fi
+      #     fi
+
+      #     x=$(( x + 2 ))
+      #     y=$(( y + 2 ))
       #   done
       # fi
 
-      echo -e "/<qemu:commandline>"
+      echo -e "${qemu_end_tag}\n"
+
+      if "${DUMP_XML}"; then
+        dump_xml_file_contents+=( "${qemu_end_tag}" )
+
+        if ! write_ref_enum_to_file "dump_xml_file_contents" "${XML_DEST_PATH}"; then
+          print_error_to_log "Could not dump XML output to file '${XML_DEST_PATH}'."
+          return 1
+        fi
+
+        print_pass_to_log "Dumped XML output to file '${XML_DEST_PATH}'."
+      fi
     }
 
     function prepare_files
@@ -581,7 +707,9 @@
 
           if "${OUTPUT_EVENT_PATHS}"; then
             file1_cgroups_output+=( "    \"/dev/input/${event_device}\"," )
-          else
+          fi
+
+          if "${OUTPUT_INPUT_PATHS}"; then
             file1_cgroups_output+=( "    \"/dev/input/by-id/${input_device}\"," )
           fi
         done
@@ -591,7 +719,9 @@
 
           if "${OUTPUT_EVENT_PATHS}"; then
             file1_cgroups_output+=( "    \"/dev/input/${event_device}\"," )
-          else
+          fi
+
+          if "${OUTPUT_INPUT_PATHS}"; then
             file1_cgroups_output+=( "    \"/dev/input/by-id/${input_device}\"," )
           fi
         done
@@ -601,7 +731,9 @@
 
         #   if "${OUTPUT_EVENT_PATHS}"; then
         #     file1_cgroups_output+=( "    \"/dev/input/${event_device}\"," )
-        #   else
+        #   fi
+
+        #   if "${OUTPUT_INPUT_PATHS}"; then
         #     file1_cgroups_output+=( "    \"/dev/input/by-id/${input_device}\"," )
         #   fi
         # done
@@ -664,31 +796,6 @@
         return 1
       fi
     }
-
-  function is_sudo_user
-  {
-    if [[ $( whoami ) != "root" ]]; then
-      print_error_to_log "User is not sudo or root."
-      return 1
-    fi
-  }
-
-  function main
-  {
-    if ! is_sudo_user \
-      || ! get_options "$@" \
-      || ! get_evdev \
-      || ! sort_evdev \
-      || ! print_evdev \
-      || ! prepare_files; then
-      return 1
-    fi
-
-    if ! write_to_files; then
-      print_fail_to_log "Could not generate Evdev setup."
-      return 1
-    fi
-  }
 # </functions>
 
 main "$@"
